// This file is autogenerated with https://github.com/acheroncrypto/native-to-anchor

use anchor_lang::prelude::*;

declare_id!("4dUGnkre6uBhX1abB4ofkoecGN4aDXdiWSaWLUjVw6bh");

#[program]
pub mod spl_associated_token {
    use super::*;

    pub fn create(ctx: Context<Create>) -> Result<()> {
        Ok(())
    }
}

#[derive(Accounts)]
pub struct Create<'info> {
    #[account(mut)]
    authority: Signer<'info>,
    #[account(mut)]
    /// CHECK:
    associated_account: AccountInfo<'info>,
    /// CHECK:
    owner: AccountInfo<'info>,
    /// CHECK:
    mint: AccountInfo<'info>,
    /// CHECK:
    system_program: AccountInfo<'info>,
    /// CHECK:
    token_program: AccountInfo<'info>,
    /// CHECK:
    rent: AccountInfo<'info>,
}
