[package]
name            = "anchor-attribute-constant"
version         = "0.28.0"
authors         = { workspace = true }
repository      = { workspace = true }
license         = { workspace = true }
description     = "Anchor attribute macro for creating constant types"
rust-version    = { workspace = true }
edition         = { workspace = true }

[lib]
proc-macro = true

[features]
idl-build = ["anchor-syn/idl-build"]
anchor-debug = ["anchor-syn/anchor-debug"]

[dependencies]
anchor-syn  = { workspace = true }
proc-macro2 = { workspace = true }
quote       = { workspace = true }
syn         = { workspace = true, features = ["full"] }
