name: "Merge Anchor Upstream"
description: "Merge Anchor Upstream"

inputs:
  repo-token:
    description: "Token with permissions to do repo things"
  workflow-token:
    description: "Token for workflow bs"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        ref: master # set the branch to merge to
        fetch-depth: 0
    - run: git config --global user.email "Elias.cmoreno17@gmail.com"
      shell: bash
    - run: git config --global user.name "Eliascm17"
      shell: bash
    - run: git remote add upstream https://github.com/project-serum/anchor.git
      shell: bash
    - run: git pull upstream master --no-ff
      shell: bash
    - run: git push origin master
      shell: bash
    - run: git checkout -b latest
      shell: bash
    - run: git merge master
      shell: bash
    - name: Check jq
      run: |
        jq --version
      shell: bash
    - name: Get Latest Tag
      run: curl -sL https://api.github.com/repos/solana-labs/solana/releases/latest | jq -r ".tag_name" > .github/releases/solana-latest.txt
      shell: bash
    - run: chmod u+x ./.github/scripts/update.sh
      shell: bash
    - run: ./.github/scripts/update.sh
      shell: bash
    - run: git add .
      shell: bash
    - run: git commit -m 'updating solana deps'
      shell: bash
    - run: git push -f origin latest
      shell: bash
