[package]
name = "basic-5"
version = "0.1.0"
edition = "2021"
rust-version = "1.60"
description = "Created with Anchor"

[lib]
crate-type = ["cdylib", "lib"]
name = "basic_5"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
anchor-lang = { workspace = true }
