[package]
name = "tic-tac-toe"
version = "0.1.0"
edition = "2018"
description = "Created with Anchor"

[lib]
crate-type = ["cdylib", "lib"]
name = "tic_tac_toe"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
