name: Merge Upstream

on:
  push:
  # schedule:
  #   - cron: "*/30 * * * *"

jobs:
  merge-upstream:
    name: Merge Upstream
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/merge-upstream/
        env:
          GITHUB_TOKEN: ${{ github.token }}
