name: Merge Upstream

on:
  push:
  # schedule:
  #   - cron: "*/30 * * * *"

jobs:
  merge-upstream:
    name: Merge Upstream
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/merge-upstream/
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
