name: No Cashing Tests

on:
  push:
    branches:
      - master
env:
  SOLANA_CLI_VERSION: 1.14.11
  NODE_VERSION: 17.0.1
  CARGO_PROFILE: release
  ANCHOR_BINARY_NAME: anchor-binary-no-caching

jobs:
  no-caching-tests:
    name: No Caching Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: ./.github/workflows/tests-reusable.yml
        with:
          cache: false
          solana_cli_version: ${{ env.SOLANA_CLI_VERSION }}
          node_version: ${{ env.NODE_VERSION }}
          cargo_profile: ${{ env.CARGO_PROFILE }}
          anchor_binary_name: ${{ env.ANCHOR_BINARY_NAME }}