name: No Cashing Tests

on:
  push:
    branches:
      - master

jobs:
  no-caching-tests:
    name: No Caching Tests
    uses: ./.github/workflows/tests-reusable.yaml
    with:
      cache: false
      solana_cli_version: 1.14.11
      node_version: 17.0.1
      cargo_profile: release
      anchor_binary_name: anchor-binary-no-caching